#############################################################################
# Makefile for building: airtame-browser
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  airtame-browser.pro
# Template: app
# Command: /usr/local/Qt-5.3.1/bin/qmake -o Makefile airtame-browser.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-gcc
CXX           = /home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_SENSORS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/airtame/build/qt5rpi/sysroot -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/airtame/build/qt5rpi/sysroot -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/local/Qt-5.3.1/mkspecs/devices/linux-rasp-pi-g++ -I. -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtQuick -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtMultimediaWidgets -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtOpenGL -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtPrintSupport -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtQml -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtMultimedia -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtPositioning -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtSensors -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui -I../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore -I. -I/home/airtame/build/qt5rpi/sysroot/opt/vc/include -I/home/airtame/build/qt5rpi/sysroot/opt/vc/include/interface/vcos/pthreads -I/home/airtame/build/qt5rpi/sysroot/opt/vc/include/interface/vmcs_host/linux -I.
LINK          = /home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-rpath-link,/home/airtame/build/qt5rpi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/airtame/build/qt5rpi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/airtame/build/qt5rpi/sysroot/lib/arm-linux-gnueabihf --sysroot=/home/airtame/build/qt5rpi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/Qt-5.3.1/lib -Wl,-rpath-link,/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib
LIBS          = $(SUBLIBS) -L/home/airtame/build/qt5rpi/sysroot/opt/vc/lib -L/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib -lQt5WebKitWidgets -L/usr/local/Qt-5.3.1/lib -lQt5Quick -lQt5MultimediaWidgets -lQt5OpenGL -lQt5PrintSupport -lQt5WebKit -lQt5Qml -lQt5Multimedia -lQt5Widgets -lQt5Network -lQt5Positioning -lQt5Sensors -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
AR            = /home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Qt-5.3.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = /home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/bin/arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		window.cpp moc_window.cpp
OBJECTS       = main.o \
		window.o \
		moc_window.o
DIST          = /usr/local/Qt-5.3.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.3.1/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.3.1/mkspecs/qdevice.pri \
		/usr/local/Qt-5.3.1/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.3.1/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/Qt-5.3.1/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/Qt-5.3.1/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/Qt-5.3.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.3.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/usr/local/Qt-5.3.1/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/uic.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/lex.prf \
		airtame-browser.pro main.cpp \
		window.cpp
QMAKE_TARGET  = airtame-browser
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = airtame-browser


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_window.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: airtame-browser.pro /usr/local/Qt-5.3.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf /usr/local/Qt-5.3.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.3.1/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/unix.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/linux.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.3.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.3.1/mkspecs/qdevice.pri \
		/usr/local/Qt-5.3.1/mkspecs/features/device_config.prf \
		/usr/local/Qt-5.3.1/mkspecs/devices/common/linux_device_pre.conf \
		/usr/local/Qt-5.3.1/mkspecs/devices/common/linux_device_post.conf \
		/usr/local/Qt-5.3.1/mkspecs/devices/common/linux_arm_device_post.conf \
		/usr/local/Qt-5.3.1/mkspecs/qconfig.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.3.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.3.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/usr/local/Qt-5.3.1/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/qt.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/resources.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/moc.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/uic.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.3.1/mkspecs/features/lex.prf \
		airtame-browser.pro \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5WebKitWidgets.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5WebKit.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Network.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Core.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Gui.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Widgets.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Quick.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Qml.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5MultimediaWidgets.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Multimedia.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5OpenGL.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5PrintSupport.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Positioning.prl \
		/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Sensors.prl
	$(QMAKE) -o Makefile airtame-browser.pro
/usr/local/Qt-5.3.1/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.3.1/mkspecs/common/shell-unix.conf:
/usr/local/Qt-5.3.1/mkspecs/common/unix.conf:
/usr/local/Qt-5.3.1/mkspecs/common/linux.conf:
/usr/local/Qt-5.3.1/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.3.1/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.3.1/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.3.1/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.3.1/mkspecs/qdevice.pri:
/usr/local/Qt-5.3.1/mkspecs/features/device_config.prf:
/usr/local/Qt-5.3.1/mkspecs/devices/common/linux_device_pre.conf:
/usr/local/Qt-5.3.1/mkspecs/devices/common/linux_device_post.conf:
/usr/local/Qt-5.3.1/mkspecs/devices/common/linux_arm_device_post.conf:
/usr/local/Qt-5.3.1/mkspecs/qconfig.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_enginio.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.3.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt-5.3.1/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.3.1/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.3.1/mkspecs/devices/linux-rasp-pi-g++/qmake.conf:
/usr/local/Qt-5.3.1/mkspecs/features/spec_post.prf:
/usr/local/Qt-5.3.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.3.1/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.3.1/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.3.1/mkspecs/features/default_post.prf:
/usr/local/Qt-5.3.1/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.3.1/mkspecs/features/qt.prf:
/usr/local/Qt-5.3.1/mkspecs/features/resources.prf:
/usr/local/Qt-5.3.1/mkspecs/features/moc.prf:
/usr/local/Qt-5.3.1/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.3.1/mkspecs/features/uic.prf:
/usr/local/Qt-5.3.1/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.3.1/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.3.1/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.3.1/mkspecs/features/yacc.prf:
/usr/local/Qt-5.3.1/mkspecs/features/lex.prf:
airtame-browser.pro:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5WebKitWidgets.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5WebKit.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Network.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Core.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Gui.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Widgets.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Quick.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Qml.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5MultimediaWidgets.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Multimedia.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5OpenGL.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5PrintSupport.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Positioning.prl:
/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/lib/libQt5Sensors.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile airtame-browser.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/airtame-browser1.0.0 || mkdir -p .tmp/airtame-browser1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/airtame-browser1.0.0/ && $(COPY_FILE) --parents window.h .tmp/airtame-browser1.0.0/ && $(COPY_FILE) --parents main.cpp window.cpp .tmp/airtame-browser1.0.0/ && $(COPY_FILE) --parents window.ui .tmp/airtame-browser1.0.0/ && (cd `dirname .tmp/airtame-browser1.0.0` && $(TAR) airtame-browser1.0.0.tar airtame-browser1.0.0 && $(COMPRESS) airtame-browser1.0.0.tar) && $(MOVE) `dirname .tmp/airtame-browser1.0.0`/airtame-browser1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/airtame-browser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp
moc_window.cpp: ../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QUrl \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qurl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbytearray.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qrefcount.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qglobal.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qconfig.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfeatures.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsystemdetection.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qprocessordetection.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcompilerdetection.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtypeinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtypetraits.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsysinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlogging.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qflags.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qglobalstatic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmutex.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qnumeric.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbasicatomic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_bootstrap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qgenericatomic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_msvc.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_armv7.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_armv6.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_armv5.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_ia64.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_mips.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_x86.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_cxx11.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_gcc.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_unix.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qnamespace.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qarraydata.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstring.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qchar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringbuilder.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobjectdefs.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobjectdefs_impl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlist.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qalgorithms.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qiterator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpair.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qurlquery.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qshareddata.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringlist.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdatastream.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qscopedpointer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qiodevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobject.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcoreevent.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmetatype.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvarlengtharray.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcontainerfwd.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qisenum.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobject_impl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qregexp.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringmatcher.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QWidget \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qwindowdefs.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qwindowdefs_win.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmargins.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpaintdevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qrect.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsize.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpoint.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpalette.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qcolor.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qrgb.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qbrush.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvector.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qmatrix.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpolygon.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qregion.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qline.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtransform.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpainterpath.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qimage.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpixmap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsharedpointer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsharedpointer_impl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qhash.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfont.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfontmetrics.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfontinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qsizepolicy.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qcursor.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qkeysequence.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qevent.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvariant.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdebug.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtextstream.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlocale.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qset.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcontiguouscache.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfile.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfiledevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qvector2d.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtouchdevice.h \
		ui_window.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QVariant \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/QWebView \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/qwebview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit/qwebkitglobal.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/qwebpage.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit/qwebsettings.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qicon.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpainter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextoption.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpen.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qnetworkaccessmanager.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QObject \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/QSslConfiguration \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslconfiguration.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslsocket.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qtcpsocket.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qabstractsocket.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslerror.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslcertificate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcryptographichash.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdatetime.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qssl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QFlags \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QAction \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qaction.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qactiongroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QApplication \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qapplication.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcoreapplication.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qeventloop.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdesktopwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qguiapplication.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qinputmethod.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QButtonGroup \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qbuttongroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QHeaderView \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qheaderview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractitemview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractscrollarea.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qframe.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qabstractitemmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qitemselectionmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractitemdelegate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstyleoption.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractspinbox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qvalidator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qregularexpression.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qslider.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractslider.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstyle.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtabbar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtabwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qrubberband.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QVBoxLayout \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qboxlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlayoutitem.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgridlayout.h \
		window.h
	/usr/local/Qt-5.3.1/bin/moc $(DEFINES) -I/usr/local/Qt-5.3.1/mkspecs/devices/linux-rasp-pi-g++ -I/home/airtame/build/airtame-browser -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtQuick -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtMultimediaWidgets -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtOpenGL -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtPrintSupport -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtQml -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtMultimedia -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtPositioning -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtSensors -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui -I/home/airtame/build/qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore -I/home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include/c++/4.7.2 -I/home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include/c++/4.7.2/arm-linux-gnueabihf -I/home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include/c++/4.7.2/backward -I/home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.7.2/include -I/home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.7.2/include-fixed -I/home/airtame/build/qt5rpi/gcc-4.7-linaro-rpi-gnueabihf/arm-linux-gnueabihf/include -I/home/airtame/build/qt5rpi/sysroot/usr/include window.h -o moc_window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_window.h
compiler_uic_clean:
	-$(DEL_FILE) ui_window.h
ui_window.h: window.ui
	/usr/local/Qt-5.3.1/bin/uic window.ui -o ui_window.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QtWidgets \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QtWidgetsDepends \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QtCore \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QtCoreDepends \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qabstractanimation.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobject.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobjectdefs.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qnamespace.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qglobal.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qconfig.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfeatures.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsystemdetection.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qprocessordetection.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcompilerdetection.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtypeinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtypetraits.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsysinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlogging.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qflags.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbasicatomic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_bootstrap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qgenericatomic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_msvc.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_armv7.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_armv6.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_armv5.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_ia64.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_mips.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_x86.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_cxx11.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_gcc.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_unix.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qglobalstatic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmutex.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qnumeric.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobjectdefs_impl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstring.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qchar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbytearray.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qrefcount.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qarraydata.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringbuilder.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlist.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qalgorithms.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qiterator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcoreevent.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qscopedpointer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmetatype.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvarlengtharray.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcontainerfwd.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qisenum.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobject_impl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qanimationgroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qparallelanimationgroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpauseanimation.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpropertyanimation.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvariantanimation.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qeasingcurve.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvector.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpoint.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvariant.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpair.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdebug.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qhash.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtextstream.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qiodevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlocale.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qshareddata.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qset.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcontiguouscache.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringlist.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdatastream.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qregexp.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringmatcher.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsequentialanimationgroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtextcodec.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qendian.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlibraryinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdatetime.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsharedpointer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsharedpointer_impl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbuffer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdir.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfileinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfile.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfiledevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdiriterator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfileselector.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QObject \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QStringList \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfilesystemwatcher.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlockfile.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qloggingcategory.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qprocess.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qresource.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsavefile.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsettings.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstandardpaths.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtemporarydir.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QScopedPointer \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtemporaryfile.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qurl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qurlquery.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qabstractitemmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qabstractproxymodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qidentityproxymodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qitemselectionmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsortfilterproxymodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringlistmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qjsonarray.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qjsonvalue.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qjsondocument.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qjsonobject.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qabstracteventdispatcher.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qeventloop.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qabstractnativeeventfilter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbasictimer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcoreapplication.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmath.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmetaobject.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmimedata.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobjectcleanuphandler.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpointer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsharedmemory.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsignalmapper.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsocketnotifier.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsystemsemaphore.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtimer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtranslator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qwineventnotifier.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmimedatabase.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmimetype.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfactoryinterface.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlibrary.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qplugin.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpluginloader.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/quuid.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qabstractstate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qabstracttransition.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qeventtransition.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfinalstate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qhistorystate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsignaltransition.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstatemachine.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qexception.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfuture.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfutureinterface.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qrunnable.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qresultstore.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfuturesynchronizer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfuturewatcher.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qreadwritelock.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsemaphore.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qthread.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qthreadpool.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qthreadstorage.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qwaitcondition.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qarraydataops.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qarraydatapointer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbitarray.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbytearraymatcher.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcache.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcollator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcommandlineoption.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcommandlineparser.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcryptographichash.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qelapsedtimer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qline.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlinkedlist.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmargins.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmessageauthenticationcode.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qqueue.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qrect.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsize.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qregularexpression.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qscopedvaluerollback.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstack.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtextboundaryfinder.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtimeline.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtimezone.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qxmlstream.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtcoreversion.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/QtGui \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/QtGuiDepends \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qaccessible.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qcolor.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qrgb.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qevent.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qwindowdefs.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qwindowdefs_win.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qregion.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qkeysequence.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qvector2d.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtouchdevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qaccessiblebridge.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qaccessibleobject.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qaccessibleplugin.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qbitmap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpixmap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpaintdevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qimage.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtransform.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qmatrix.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpolygon.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpainterpath.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qicon.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qiconengine.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qiconengineplugin.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qimageiohandler.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qimagereader.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qimagewriter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qmovie.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpicture.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpictureformatplugin.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpixmapcache.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qstandarditemmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qbrush.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfont.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qclipboard.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qcursor.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qdrag.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qgenericplugin.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qgenericpluginfactory.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qguiapplication.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qinputmethod.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qoffscreensurface.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qsurface.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qsurfaceformat.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglcontext.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/QSurfaceFormat \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopengl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qt_windows.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopengles2ext.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglext.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglversionfunctions.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpalette.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qscreen.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QList \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QRect \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QSize \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QSizeF \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/QTransform \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qsessionmanager.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qstylehints.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qwindow.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QEvent \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QMargins \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qgenericmatrix.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qmatrix4x4.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qvector3d.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qvector4d.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qquaternion.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglbuffer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopengldebug.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglframebufferobject.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglfunctions.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglpaintdevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglpixeltransferoptions.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QSharedDataPointer \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglshaderprogram.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopengltexture.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopengltimerquery.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qopenglvertexarrayobject.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qbackingstore.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpagedpaintdevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpagelayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpagesize.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpaintengine.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpainter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextoption.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpen.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfontinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfontmetrics.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpdfwriter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qabstracttextdocumentlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextformat.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qglyphrun.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qrawfont.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfontdatabase.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextcursor.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextdocument.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qstatictext.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qsyntaxhighlighter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextobject.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextdocumentfragment.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextdocumentwriter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextlist.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtexttable.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qdesktopservices.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qvalidator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtguiversion.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qaccessiblewidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qcolordialog.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdialog.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qsizepolicy.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qerrormessage.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qfiledialog.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qfilesystemmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qfontdialog.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qinputdialog.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlineedit.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qframe.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qmessagebox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qprogressdialog.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qwizard.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicseffect.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicsanchorlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicsitem.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicslayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicslayoutitem.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicsgridlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicsitemanimation.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicslinearlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicsproxywidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicswidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicsscene.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicssceneevent.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicstransform.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/QVector3D \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/QMatrix4x4 \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgraphicsview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qscrollarea.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractscrollarea.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractitemdelegate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstyleoption.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractspinbox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qslider.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractslider.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstyle.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtabbar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtabwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qrubberband.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractitemview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qcolumnview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdatawidgetmapper.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdirmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qfileiconprovider.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qheaderview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qitemdelegate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qitemeditorfactory.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlistview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlistwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstyleditemdelegate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtableview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtablewidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtreeview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtreewidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtreewidgetitemiterator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qaction.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qactiongroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qapplication.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdesktopwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qboxlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlayoutitem.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgridlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qformlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QLayout \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgesture.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgesturerecognizer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qshortcut.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstackedlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtooltip.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qwhatsthis.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qwidgetaction.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qkeyeventtransition.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qmouseeventtransition.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qcommonstyle.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdrawutil.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qproxystyle.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QCommonStyle \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstylefactory.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstylepainter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstyleplugin.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qcolormap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qcompleter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qscroller.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QPointF \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QScrollerProperties \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qscrollerproperties.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QMetaType \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QVariant \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qsystemtrayicon.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qundogroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qundostack.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qundoview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractbutton.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qbuttongroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qcalendarwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qcheckbox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qcombobox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qcommandlinkbutton.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qpushbutton.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdatetimeedit.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdial.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdialogbuttonbox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdockwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qfocusframe.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qfontcombobox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgroupbox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qkeysequenceedit.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlabel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlcdnumber.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qmainwindow.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qmdiarea.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qmdisubwindow.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qmenu.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qmenubar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qplaintextedit.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtextedit.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qprogressbar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qradiobutton.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qscrollbar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qsizegrip.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qspinbox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qsplashscreen.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qsplitter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstackedwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstatusbar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtextbrowser.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtoolbar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtoolbox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtoolbutton.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtwidgetsversion.h \
		window.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QUrl \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QWidget \
		ui_window.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/QWebView \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/qwebview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit/qwebkitglobal.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/qwebpage.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit/qwebsettings.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qnetworkaccessmanager.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/QSslConfiguration \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslconfiguration.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslsocket.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qtcpsocket.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qabstractsocket.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslerror.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslcertificate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qssl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QFlags \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QAction \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QApplication \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QButtonGroup \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QHeaderView \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QVBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

window.o: window.cpp ../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit/QWebElement \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit/qwebelement.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstring.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qchar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qglobal.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qconfig.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfeatures.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsystemdetection.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qprocessordetection.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcompilerdetection.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtypeinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtypetraits.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsysinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlogging.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qflags.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbasicatomic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_bootstrap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qgenericatomic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_msvc.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_armv7.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_armv6.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_armv5.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_ia64.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_mips.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_x86.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_cxx11.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_gcc.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qatomic_unix.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qglobalstatic.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmutex.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qnumeric.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qbytearray.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qrefcount.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qnamespace.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qarraydata.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringbuilder.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringlist.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qalgorithms.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdatastream.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qscopedpointer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qiodevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobject.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobjectdefs.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobjectdefs_impl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlist.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qiterator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcoreevent.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmetatype.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvarlengtharray.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcontainerfwd.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qisenum.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qobject_impl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpair.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qregexp.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qstringmatcher.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qrect.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmargins.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsize.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qpoint.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvariant.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qmap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdebug.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qhash.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qtextstream.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qlocale.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qshareddata.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qvector.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qset.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcontiguouscache.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit/qwebkitglobal.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/QWebFrame \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/qwebframe.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qurl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qurlquery.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qicon.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpixmap.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpaintdevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qwindowdefs.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qwindowdefs_win.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qcolor.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qrgb.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsharedpointer.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qsharedpointer_impl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qimage.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtransform.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qmatrix.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpolygon.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qregion.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qline.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpainterpath.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qnetworkaccessmanager.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QObject \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/QSslConfiguration \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslconfiguration.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslsocket.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qtcpsocket.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qabstractsocket.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslerror.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qsslcertificate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcryptographichash.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qdatetime.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtNetwork/qssl.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QFlags \
		window.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QUrl \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QWidget \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpalette.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qbrush.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfont.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfontmetrics.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qfontinfo.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qsizepolicy.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qcursor.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qkeysequence.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qevent.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfile.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qfiledevice.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qvector2d.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtouchdevice.h \
		ui_window.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/QVariant \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/QWebView \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/qwebview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKitWidgets/qwebpage.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWebKit/qwebsettings.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpainter.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qtextoption.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qpen.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QAction \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qaction.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qactiongroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QApplication \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qapplication.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qcoreapplication.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qeventloop.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qdesktopwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qguiapplication.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qinputmethod.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QButtonGroup \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qbuttongroup.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QHeaderView \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qheaderview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractitemview.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractscrollarea.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qframe.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qabstractitemmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qitemselectionmodel.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractitemdelegate.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstyleoption.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractspinbox.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtGui/qvalidator.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtCore/qregularexpression.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qslider.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qabstractslider.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qstyle.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtabbar.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qtabwidget.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qrubberband.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/QVBoxLayout \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qboxlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlayout.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qlayoutitem.h \
		../qt5rpi/sysroot/usr/local/Qt-5.3.1/include/QtWidgets/qgridlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

